// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/discord-gophers/goapi-gen version v0.2.2 DO NOT EDIT.
package server

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"encoding/xml"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/discord-gophers/goapi-gen/runtime"
	openapi_types "github.com/discord-gophers/goapi-gen/types"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/go-chi/render"
)

const (
	TeamLeadScopes = "team_lead.Scopes"
	UserScopes     = "user.Scopes"
)

// Defines values for TransactionStatus.
var (
	UnknownTransactionStatus = TransactionStatus{}

	TransactionStatusN0 = TransactionStatus{0}

	TransactionStatusN1 = TransactionStatus{1}

	TransactionStatusN2 = TransactionStatus{2}

	TransactionStatusN3 = TransactionStatus{3}
)

// Defines values for TransactionType.
var (
	UnknownTransactionType = TransactionType{}

	TransactionTypeN0 = TransactionType{0}

	TransactionTypeN1 = TransactionType{1}

	TransactionTypeN2 = TransactionType{2}
)

// Account defines model for Account.
type Account struct {
	Active         bool                `json:"active"`
	Allocated      int                 `json:"allocated"`
	AllocationDate time.Time           `json:"allocation_date"`
	Balance        int                 `json:"balance"`
	CreationDate   time.Time           `json:"creation_date"`
	Creator        string              `json:"creator"`
	ExpiryDate     time.Time           `json:"expiry_date"`
	ID             string              `json:"id"`
	Name           string              `json:"name"`
	Pending        int                 `json:"pending"`
	PointOfContact openapi_types.Email `json:"point_of_contact"`
	Source         string              `json:"source"`
	Used           int                 `json:"used"`
	WaterlooID     string              `json:"waterloo_id"`
}

// EditTransaction defines model for EditTransaction.
type EditTransaction struct {
	Approver string `json:"approver"`
	ID       string `json:"id"`
	Name     string `json:"name"`
	Notes    string `json:"notes"`
}

// NewAccount defines model for NewAccount.
type NewAccount struct {
	Active         bool                `json:"active"`
	AllocationDate time.Time           `json:"allocation_date"`
	Creator        string              `json:"creator"`
	ExpiryDate     time.Time           `json:"expiry_date"`
	ID             string              `json:"id"`
	Name           string              `json:"name"`
	PointOfContact openapi_types.Email `json:"point_of_contact"`
	Source         string              `json:"source"`
	WaterlooID     string              `json:"waterloo_id"`
}

// NewTransaction defines model for NewTransaction.
type NewTransaction struct {
	AccountID string            `json:"account_id"`
	Amount    int               `json:"amount"`
	ID        string            `json:"id"`
	Name      string            `json:"name"`
	Notes     string            `json:"notes"`
	Status    TransactionStatus `json:"status"`
	Type      TransactionType   `json:"type"`
}

// Transaction defines model for Transaction.
type Transaction struct {
	AccountID    string            `json:"account_id"`
	Amount       int               `json:"amount"`
	ApprovalDate time.Time         `json:"approval_date"`
	CreationDate time.Time         `json:"creation_date"`
	ID           string            `json:"id"`
	Name         string            `json:"name"`
	Notes        string            `json:"notes"`
	PaymentDate  time.Time         `json:"payment_date"`
	RejectedDate time.Time         `json:"rejected_date"`
	Status       TransactionStatus `json:"status"`
	Type         TransactionType   `json:"type"`
}

// TransactionStatus defines model for TransactionStatus.
type TransactionStatus struct {
	value int
}

func (t *TransactionStatus) ToValue() int {
	return t.value
}
func (t *TransactionStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(t.value)
}
func (t *TransactionStatus) UnmarshalJSON(data []byte) error {
	var value int
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	return t.FromValue(value)
}
func (t *TransactionStatus) FromValue(value int) error {
	switch value {

	case TransactionStatusN0.value:
		t.value = value
		return nil

	case TransactionStatusN1.value:
		t.value = value
		return nil

	case TransactionStatusN2.value:
		t.value = value
		return nil

	case TransactionStatusN3.value:
		t.value = value
		return nil

	}
	return fmt.Errorf("unknown enum value: %v", value)
}

// TransactionType defines model for TransactionType.
type TransactionType struct {
	value int
}

func (t *TransactionType) ToValue() int {
	return t.value
}
func (t *TransactionType) MarshalJSON() ([]byte, error) {
	return json.Marshal(t.value)
}
func (t *TransactionType) UnmarshalJSON(data []byte) error {
	var value int
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	return t.FromValue(value)
}
func (t *TransactionType) FromValue(value int) error {
	switch value {

	case TransactionTypeN0.value:
		t.value = value
		return nil

	case TransactionTypeN1.value:
		t.value = value
		return nil

	case TransactionTypeN2.value:
		t.value = value
		return nil

	}
	return fmt.Errorf("unknown enum value: %v", value)
}

// CreateAccountJSONBody defines parameters for CreateAccount.
type CreateAccountJSONBody NewAccount

// CreateTransactionJSONBody defines parameters for CreateTransaction.
type CreateTransactionJSONBody NewTransaction

// ApproveTransactionJSONBody defines parameters for ApproveTransaction.
type ApproveTransactionJSONBody EditTransaction

// HoldTransactionJSONBody defines parameters for HoldTransaction.
type HoldTransactionJSONBody EditTransaction

// PayTransactionJSONBody defines parameters for PayTransaction.
type PayTransactionJSONBody EditTransaction

// RejectTransactionJSONBody defines parameters for RejectTransaction.
type RejectTransactionJSONBody EditTransaction

// CreateAccountJSONRequestBody defines body for CreateAccount for application/json ContentType.
type CreateAccountJSONRequestBody CreateAccountJSONBody

// Bind implements render.Binder.
func (CreateAccountJSONRequestBody) Bind(*http.Request) error {
	return nil
}

// CreateTransactionJSONRequestBody defines body for CreateTransaction for application/json ContentType.
type CreateTransactionJSONRequestBody CreateTransactionJSONBody

// Bind implements render.Binder.
func (CreateTransactionJSONRequestBody) Bind(*http.Request) error {
	return nil
}

// ApproveTransactionJSONRequestBody defines body for ApproveTransaction for application/json ContentType.
type ApproveTransactionJSONRequestBody ApproveTransactionJSONBody

// Bind implements render.Binder.
func (ApproveTransactionJSONRequestBody) Bind(*http.Request) error {
	return nil
}

// HoldTransactionJSONRequestBody defines body for HoldTransaction for application/json ContentType.
type HoldTransactionJSONRequestBody HoldTransactionJSONBody

// Bind implements render.Binder.
func (HoldTransactionJSONRequestBody) Bind(*http.Request) error {
	return nil
}

// PayTransactionJSONRequestBody defines body for PayTransaction for application/json ContentType.
type PayTransactionJSONRequestBody PayTransactionJSONBody

// Bind implements render.Binder.
func (PayTransactionJSONRequestBody) Bind(*http.Request) error {
	return nil
}

// RejectTransactionJSONRequestBody defines body for RejectTransaction for application/json ContentType.
type RejectTransactionJSONRequestBody RejectTransactionJSONBody

// Bind implements render.Binder.
func (RejectTransactionJSONRequestBody) Bind(*http.Request) error {
	return nil
}

// Response is a common response struct for all the API calls.
// A Response object may be instantiated via functions for specific operation responses.
// It may also be instantiated directly, for the purpose of responding with a single status code.
type Response struct {
	body        interface{}
	Code        int
	contentType string
}

// Render implements the render.Renderer interface. It sets the Content-Type header
// and status code based on the response definition.
func (resp *Response) Render(w http.ResponseWriter, r *http.Request) error {
	w.Header().Set("Content-Type", resp.contentType)
	render.Status(r, resp.Code)
	return nil
}

// Status is a builder method to override the default status code for a response.
func (resp *Response) Status(code int) *Response {
	resp.Code = code
	return resp
}

// ContentType is a builder method to override the default content type for a response.
func (resp *Response) ContentType(contentType string) *Response {
	resp.contentType = contentType
	return resp
}

// MarshalJSON implements the json.Marshaler interface.
// This is used to only marshal the body of the response.
func (resp *Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(resp.body)
}

// MarshalXML implements the xml.Marshaler interface.
// This is used to only marshal the body of the response.
func (resp *Response) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return e.Encode(resp.body)
}

// ListAccountsJSON200Response is a constructor method for a ListAccounts response.
// A *Response is returned with the configured status code and content type from the spec.
func ListAccountsJSON200Response(body []Account) *Response {
	return &Response{
		body:        body,
		Code:        200,
		contentType: "application/json",
	}
}

// CreateAccountJSON200Response is a constructor method for a CreateAccount response.
// A *Response is returned with the configured status code and content type from the spec.
func CreateAccountJSON200Response(body Account) *Response {
	return &Response{
		body:        body,
		Code:        200,
		contentType: "application/json",
	}
}

// GetRolesUserIDJSON200Response is a constructor method for a GetRolesUserID response.
// A *Response is returned with the configured status code and content type from the spec.
func GetRolesUserIDJSON200Response(body []Transaction) *Response {
	return &Response{
		body:        body,
		Code:        200,
		contentType: "application/json",
	}
}

// CreateTransactionJSON200Response is a constructor method for a CreateTransaction response.
// A *Response is returned with the configured status code and content type from the spec.
func CreateTransactionJSON200Response(body Transaction) *Response {
	return &Response{
		body:        body,
		Code:        200,
		contentType: "application/json",
	}
}

// ListTransactionsJSON200Response is a constructor method for a ListTransactions response.
// A *Response is returned with the configured status code and content type from the spec.
func ListTransactionsJSON200Response(body []Transaction) *Response {
	return &Response{
		body:        body,
		Code:        200,
		contentType: "application/json",
	}
}

// ListAllTransactionsJSON200Response is a constructor method for a ListAllTransactions response.
// A *Response is returned with the configured status code and content type from the spec.
func ListAllTransactionsJSON200Response(body []Transaction) *Response {
	return &Response{
		body:        body,
		Code:        200,
		contentType: "application/json",
	}
}

// ListRejectedTransactionsJSON200Response is a constructor method for a ListRejectedTransactions response.
// A *Response is returned with the configured status code and content type from the spec.
func ListRejectedTransactionsJSON200Response(body []Transaction) *Response {
	return &Response{
		body:        body,
		Code:        200,
		contentType: "application/json",
	}
}

// ApproveTransactionJSON200Response is a constructor method for a ApproveTransaction response.
// A *Response is returned with the configured status code and content type from the spec.
func ApproveTransactionJSON200Response(body []Transaction) *Response {
	return &Response{
		body:        body,
		Code:        200,
		contentType: "application/json",
	}
}

// HoldTransactionJSON200Response is a constructor method for a HoldTransaction response.
// A *Response is returned with the configured status code and content type from the spec.
func HoldTransactionJSON200Response(body []Transaction) *Response {
	return &Response{
		body:        body,
		Code:        200,
		contentType: "application/json",
	}
}

// PayTransactionJSON200Response is a constructor method for a PayTransaction response.
// A *Response is returned with the configured status code and content type from the spec.
func PayTransactionJSON200Response(body []Transaction) *Response {
	return &Response{
		body:        body,
		Code:        200,
		contentType: "application/json",
	}
}

// RejectTransactionJSON200Response is a constructor method for a RejectTransaction response.
// A *Response is returned with the configured status code and content type from the spec.
func RejectTransactionJSON200Response(body []Transaction) *Response {
	return &Response{
		body:        body,
		Code:        200,
		contentType: "application/json",
	}
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Retrieve the list of available accounts.
	// (GET /accounts)
	ListAccounts(w http.ResponseWriter, r *http.Request) *Response
	// Create a new account.
	// (POST /accounts)
	CreateAccount(w http.ResponseWriter, r *http.Request) *Response
	// Auth Route For Getting the user Id
	// (GET /roles/{user_id})
	GetRolesUserID(w http.ResponseWriter, r *http.Request, userID string) *Response
	// Create a new transaction.
	// (POST /transactions)
	CreateTransaction(w http.ResponseWriter, r *http.Request) *Response
	// Retrieve the active transactions for an account.
	// (GET /transactions/{account_id})
	ListTransactions(w http.ResponseWriter, r *http.Request, accountID string) *Response
	// Retrieve all transactions, including those that are currently a request and not approved.
	// (GET /transactions/{account_id}/all)
	ListAllTransactions(w http.ResponseWriter, r *http.Request, accountID string) *Response
	// Retrieve all rejected transactions for an account.
	// (GET /transactions/{account_id}/rejected)
	ListRejectedTransactions(w http.ResponseWriter, r *http.Request, accountID string) *Response
	// Get transaction documents
	// (GET /transactions/{account_id}/{transaction_id}/ref)
	TransactionRef(w http.ResponseWriter, r *http.Request, accountID string, transactionID string) *Response
	// Approve a transaction.
	// (POST /transactions/{account_id}/{transaction_id}:approve)
	ApproveTransaction(w http.ResponseWriter, r *http.Request, accountID string, transactionID string) *Response
	// Hold back a transaction, and reset it to pending
	// (POST /transactions/{account_id}/{transaction_id}:hold)
	HoldTransaction(w http.ResponseWriter, r *http.Request, accountID string, transactionID string) *Response
	// Mark a transaction as paid.
	// (POST /transactions/{account_id}/{transaction_id}:pay)
	PayTransaction(w http.ResponseWriter, r *http.Request, accountID string, transactionID string) *Response
	// Reject a transaction.
	// (POST /transactions/{account_id}/{transaction_id}:reject)
	RejectTransaction(w http.ResponseWriter, r *http.Request, accountID string, transactionID string) *Response
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler          ServerInterface
	Middlewares      map[string]func(http.Handler) http.Handler
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// ListAccounts operation middleware
func (siw *ServerInterfaceWrapper) ListAccounts(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, UserScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.ListAccounts(w, r)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// CreateAccount operation middleware
func (siw *ServerInterfaceWrapper) CreateAccount(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, TeamLeadScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.CreateAccount(w, r)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// GetRolesUserID operation middleware
func (siw *ServerInterfaceWrapper) GetRolesUserID(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// ------------- Path parameter "user_id" -------------
	var userID string

	if err := runtime.BindStyledParameter("simple", false, "user_id", chi.URLParam(r, "user_id"), &userID); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "user_id"})
		return
	}

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.GetRolesUserID(w, r, userID)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// CreateTransaction operation middleware
func (siw *ServerInterfaceWrapper) CreateTransaction(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, UserScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.CreateTransaction(w, r)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// ListTransactions operation middleware
func (siw *ServerInterfaceWrapper) ListTransactions(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// ------------- Path parameter "account_id" -------------
	var accountID string

	if err := runtime.BindStyledParameter("simple", false, "account_id", chi.URLParam(r, "account_id"), &accountID); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "account_id"})
		return
	}

	ctx = context.WithValue(ctx, UserScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.ListTransactions(w, r, accountID)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// ListAllTransactions operation middleware
func (siw *ServerInterfaceWrapper) ListAllTransactions(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// ------------- Path parameter "account_id" -------------
	var accountID string

	if err := runtime.BindStyledParameter("simple", false, "account_id", chi.URLParam(r, "account_id"), &accountID); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "account_id"})
		return
	}

	ctx = context.WithValue(ctx, TeamLeadScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.ListAllTransactions(w, r, accountID)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// ListRejectedTransactions operation middleware
func (siw *ServerInterfaceWrapper) ListRejectedTransactions(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// ------------- Path parameter "account_id" -------------
	var accountID string

	if err := runtime.BindStyledParameter("simple", false, "account_id", chi.URLParam(r, "account_id"), &accountID); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "account_id"})
		return
	}

	ctx = context.WithValue(ctx, TeamLeadScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.ListRejectedTransactions(w, r, accountID)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// TransactionRef operation middleware
func (siw *ServerInterfaceWrapper) TransactionRef(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// ------------- Path parameter "account_id" -------------
	var accountID string

	if err := runtime.BindStyledParameter("simple", false, "account_id", chi.URLParam(r, "account_id"), &accountID); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "account_id"})
		return
	}

	// ------------- Path parameter "transaction_id" -------------
	var transactionID string

	if err := runtime.BindStyledParameter("simple", false, "transaction_id", chi.URLParam(r, "transaction_id"), &transactionID); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "transaction_id"})
		return
	}

	ctx = context.WithValue(ctx, TeamLeadScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.TransactionRef(w, r, accountID, transactionID)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// ApproveTransaction operation middleware
func (siw *ServerInterfaceWrapper) ApproveTransaction(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// ------------- Path parameter "account_id" -------------
	var accountID string

	if err := runtime.BindStyledParameter("simple", false, "account_id", chi.URLParam(r, "account_id"), &accountID); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "account_id"})
		return
	}

	// ------------- Path parameter "transaction_id" -------------
	var transactionID string

	if err := runtime.BindStyledParameter("simple", false, "transaction_id", chi.URLParam(r, "transaction_id"), &transactionID); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "transaction_id"})
		return
	}

	ctx = context.WithValue(ctx, TeamLeadScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.ApproveTransaction(w, r, accountID, transactionID)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// HoldTransaction operation middleware
func (siw *ServerInterfaceWrapper) HoldTransaction(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// ------------- Path parameter "account_id" -------------
	var accountID string

	if err := runtime.BindStyledParameter("simple", false, "account_id", chi.URLParam(r, "account_id"), &accountID); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "account_id"})
		return
	}

	// ------------- Path parameter "transaction_id" -------------
	var transactionID string

	if err := runtime.BindStyledParameter("simple", false, "transaction_id", chi.URLParam(r, "transaction_id"), &transactionID); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "transaction_id"})
		return
	}

	ctx = context.WithValue(ctx, TeamLeadScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.HoldTransaction(w, r, accountID, transactionID)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// PayTransaction operation middleware
func (siw *ServerInterfaceWrapper) PayTransaction(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// ------------- Path parameter "account_id" -------------
	var accountID string

	if err := runtime.BindStyledParameter("simple", false, "account_id", chi.URLParam(r, "account_id"), &accountID); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "account_id"})
		return
	}

	// ------------- Path parameter "transaction_id" -------------
	var transactionID string

	if err := runtime.BindStyledParameter("simple", false, "transaction_id", chi.URLParam(r, "transaction_id"), &transactionID); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "transaction_id"})
		return
	}

	ctx = context.WithValue(ctx, UserScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.PayTransaction(w, r, accountID, transactionID)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// RejectTransaction operation middleware
func (siw *ServerInterfaceWrapper) RejectTransaction(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// ------------- Path parameter "account_id" -------------
	var accountID string

	if err := runtime.BindStyledParameter("simple", false, "account_id", chi.URLParam(r, "account_id"), &accountID); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "account_id"})
		return
	}

	// ------------- Path parameter "transaction_id" -------------
	var transactionID string

	if err := runtime.BindStyledParameter("simple", false, "transaction_id", chi.URLParam(r, "transaction_id"), &transactionID); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "transaction_id"})
		return
	}

	ctx = context.WithValue(ctx, TeamLeadScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.RejectTransaction(w, r, accountID, transactionID)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	err       error
	paramName string
}

// Error implements error.
func (err UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter %s: %v", err.paramName, err.err)
}

func (err UnescapedCookieParamError) Unwrap() error { return err.err }

type UnmarshalingParamError struct {
	err       error
	paramName string
}

// Error implements error.
func (err UnmarshalingParamError) Error() string {
	return fmt.Sprintf("error unmarshaling parameter %s as JSON: %v", err.paramName, err.err)
}

func (err UnmarshalingParamError) Unwrap() error { return err.err }

type RequiredParamError struct {
	err       error
	paramName string
}

// Error implements error.
func (err RequiredParamError) Error() string {
	if err.err == nil {
		return fmt.Sprintf("query parameter %s is required, but not found", err.paramName)
	} else {
		return fmt.Sprintf("query parameter %s is required, but errored: %s", err.paramName, err.err)
	}
}

func (err RequiredParamError) Unwrap() error { return err.err }

type RequiredHeaderError struct {
	paramName string
}

// Error implements error.
func (err RequiredHeaderError) Error() string {
	return fmt.Sprintf("header parameter %s is required, but not found", err.paramName)
}

type InvalidParamFormatError struct {
	err       error
	paramName string
}

// Error implements error.
func (err InvalidParamFormatError) Error() string {
	return fmt.Sprintf("invalid format for parameter %s: %v", err.paramName, err.err)
}

func (err InvalidParamFormatError) Unwrap() error { return err.err }

type TooManyValuesForParamError struct {
	NumValues int
	paramName string
}

// Error implements error.
func (err TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("expected one value for %s, got %d", err.paramName, err.NumValues)
}

// ParameterName is an interface that is implemented by error types that are
// relevant to a specific parameter.
type ParameterError interface {
	error
	// ParamName is the name of the parameter that the error is referring to.
	ParamName() string
}

func (err UnescapedCookieParamError) ParamName() string  { return err.paramName }
func (err UnmarshalingParamError) ParamName() string     { return err.paramName }
func (err RequiredParamError) ParamName() string         { return err.paramName }
func (err RequiredHeaderError) ParamName() string        { return err.paramName }
func (err InvalidParamFormatError) ParamName() string    { return err.paramName }
func (err TooManyValuesForParamError) ParamName() string { return err.paramName }

type ServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      map[string]func(http.Handler) http.Handler
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

type ServerOption func(*ServerOptions)

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface, opts ...ServerOption) http.Handler {
	options := &ServerOptions{
		BaseURL:     "/",
		BaseRouter:  chi.NewRouter(),
		Middlewares: make(map[string]func(http.Handler) http.Handler),
		ErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
	}

	for _, f := range opts {
		f(options)
	}

	r := options.BaseRouter
	wrapper := ServerInterfaceWrapper{
		Handler:          si,
		Middlewares:      options.Middlewares,
		ErrorHandlerFunc: options.ErrorHandlerFunc,
	}

	r.Route(options.BaseURL, func(r chi.Router) {
		r.Get("/accounts", wrapper.ListAccounts)
		r.Post("/accounts", wrapper.CreateAccount)
		r.Get("/roles/{user_id}", wrapper.GetRolesUserID)
		r.Post("/transactions", wrapper.CreateTransaction)
		r.Get("/transactions/{account_id}", wrapper.ListTransactions)
		r.Get("/transactions/{account_id}/all", wrapper.ListAllTransactions)
		r.Get("/transactions/{account_id}/rejected", wrapper.ListRejectedTransactions)
		r.Get("/transactions/{account_id}/{transaction_id}/ref", wrapper.TransactionRef)
		r.Post("/transactions/{account_id}/{transaction_id}:approve", wrapper.ApproveTransaction)
		r.Post("/transactions/{account_id}/{transaction_id}:hold", wrapper.HoldTransaction)
		r.Post("/transactions/{account_id}/{transaction_id}:pay", wrapper.PayTransaction)
		r.Post("/transactions/{account_id}/{transaction_id}:reject", wrapper.RejectTransaction)

	})
	return r
}

func WithRouter(r chi.Router) ServerOption {
	return func(s *ServerOptions) {
		s.BaseRouter = r
	}
}

func WithServerBaseURL(url string) ServerOption {
	return func(s *ServerOptions) {
		s.BaseURL = url
	}
}

func WithMiddleware(key string, middleware func(http.Handler) http.Handler) ServerOption {
	return func(s *ServerOptions) {
		s.Middlewares[key] = middleware
	}
}

func WithMiddlewares(middlewares map[string]func(http.Handler) http.Handler) ServerOption {
	return func(s *ServerOptions) {
		s.Middlewares = middlewares
	}
}

func WithErrorHandler(handler func(w http.ResponseWriter, r *http.Request, err error)) ServerOption {
	return func(s *ServerOptions) {
		s.ErrorHandlerFunc = handler
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZXXfbNhL9K1jsPjKibL/xaZ111nHbND6O2z44Pj4jciQhAQEGGEpVdPTfewCS4oco",
	"VXLkNMnxm0wC83HvncEQXvJYp5lWqMjyaMltPMUU/M/zONa5IvczMzpDQwL9C4hJzND9okWGPOIjrSWC",
	"4quAg5Q6BsLEvU6FEmme8mgYVEuFIpygaSwVWj0kQN7eWJsUiEfcPXhBIkW+3mnJCDVxG0cgQcXNABpW",
	"Y4OPsem3adOwWb/DPzNhFgcaFEmvLQUp9r7IUCXuZ29SmRaKHvT4IdaKIKZWGJiCkH0hWJ2buN9bbjHp",
	"dzUHQiO1fuhNYBVwg59yYdz2u824aiCDSiZt/DZpX8dZgtMOwQPZlFVNf5lFDV2X/Ps1Jnr0AWNy6b1K",
	"BN0aUNZFp1WPuLPM6Bn2K+FQUpWmwupuGH2Kxdo1COs4+rL4FedfUp3fY3kcuwK+RZ1voXq3XgsdPGwB",
	"FNJKJZulfiw1B9wSUO5f/cfgmEf832F9rITlmRI28nhXbFhVCe+98dYt79LTwKA0uA5pjUDQU2V9eD8V",
	"2EU9g3xM4R1er8ejNoNFiooO9G/Q4YnJgdu+JR2VRbpVTm1CO0B1iesiUgtxS9lv5hgtOSo3TN0Ng5Pg",
	"NDi7D/yDC7Qxj/gwYv9zLjF5r96rk4hdF6ei++s0Ytcg/Iuz6KYMhPfNZF2EOk43XF5gpq2g0uUNinSU",
	"G4sOiMqx0XFu/JMej45zjHMjaPHOkVSKECFlEsGLWCge8Vjrj2LdOiNu0VqhFVs/LyjmEX8JVsS1J8jE",
	"z7goRx5/fo2lnjsvrkoONI1g0GzaXvlDkNAokBc69ikkaGMjsqKN8J+0UEznhiXCxtok/2JTosxGYVg+",
	"GMQ6DYWaCcLQfHrz6vez9Gw6dSOOkTzi+632GY21c984JYvDMeL5fA5mMhjlVii09r8T99xZqlN/Deln",
	"2HA6n88Hud/rFq+CTm63U2GZsIymyP44v7l8m1l2fn3FEhwLJdyiAQ+4FDEq6wVVOntzdbvhauoCGKSC",
	"XpTrB9pMQl/egqTbVXl4wd5mqJyfs8GQB3yGxhbxDAfDwYnbojNUkAke8bPBcHDqS5Smnp2wrHT/xwQ9",
	"Tq7P+4q9SnjEfxGWzqtFRZdASy91siikY9BmWtlCr6fDYQU6Fv0fskyK4vQPP9jiKKl0tOSCMP3bLlcN",
	"eKtab8aAl1uzbHh0tyy1fXe/ug+4zdMUzIJH/AbJCJyhp0YKS0yPGcxASBhJZBUGjh6CiW10QMvv/cxl",
	"e5ApukwVXRea/UHYlXtjvi2y/SK490K5B9VGG+pCW4DAgCmcV0BuwXEV8NBoiTZcOpoeRLLaqrpLpBu3",
	"9DeL5urCK9ZAioTG+oh8w3Iqrmu2tMmbJxmZHIMGAN3h9v4fEXRzstom6jXA5zlN2Y3OCdn/tWGXSCTU",
	"xCvZZcyukibaOU1LpKl24gPapeFmQE+m41bWT6vlrqv9ukRLyg34mnJuoboJdLisJ6fVzpZ62zS0j7xb",
	"I9mPoPAD23bxcdnkxbKxNgxUX9s5hKcQpNx9/En5TNee58GaM5CyRVbAhIplnhTNS1vHKhADgyzOjUFF",
	"csGAldkzUAlTmlh5+5M8mtzqc2Mnw9WnwDPNj6G5gvhJinPZeFUSOt7KZSPDGxw/JYNBr7F2rF9TEp9F",
	"1lbE+p5hJJTjbOOS4TDCL5Ga9LJEx3mKxTfBUXiNykrfPqucFwvaw8p3TPBxZp3uPf4RRquv3UxKYhkc",
	"Y+raFNZUy2S7ql5rmTxL6keTlGOVjSD+2BZV4OcKgxaJCWKkWf0vs+OILYPFdq1dw+JZat+l1Po/UN6A",
	"6QiMgWUZiOR43asYrrZrqhhdn2X1o3Wwgtf9z0Rv2swqzovr5BAyEc5OeMBnYMRI+tQ96qWZ7v28vwNx",
	"n2iuT6agYOL/qO9/O9f7q66iLHci6TcasDxLesxT+6trq4vWutX96q8AAAD//+5nrW+zIwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
